include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    constant_identifier_names: ignore
  exclude:
    - build/**

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declarations: true
    avoid_print: false
